### ISSUE TITLE
Group together spark config / patches

### ISSUE THREAD

**Issue by davidmcclure** [davidmcclure/osp-pipeline#4]
To keep the top-level directory clean, can we group together:

- `spark-defaults-osp.conf.template`
- `cluster-bootstrap.sh`
- `/spark_patches`

Under a shared `spark` directory, or similar? And since `pyspark_worker_hooks.py` is just used for the coverage reports (I think), maybe move this under `/tests`?

**Comment by wearpants** [comment]
pyspark_worker_hooks.py needs to stay where it is so that spark can find it
as a top-level module

On Dec 14, 2016 2:05 AM, "David McClure" <notifications@github.com> wrote:

To keep the top-level directory clean, can we group together:

   - spark-defaults-osp.conf.template
   - cluster-bootstrap.sh
   - /spark_patches

Under a shared spark directory, or similar? And since
pyspark_worker_hooks.py is just used for the coverage reports (I think),
maybe move this under /tests?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/davidmcclure/osp-pipeline/issues/4>, or mute the thread

**Comment by davidmcclure** [comment]
This is done except for `pyspark_worker_hooks.py`.
